# Use the official Nginx base image
FROM nginx

# Copy the HTML files to the Nginx document root
COPY pages/dev/statics.html /usr/share/nginx/html/

# Expose port 80 for web traffic
EXPOSE 80

# Start the Nginx server when the container launches
CMD ["nginx", "-g", "daemon off;"]